### ISSUE TITLE
[FEATURE] 내 약 리스트에 담기 버튼 기능 구현

### ISSUE THREAD

**Issue by noranbear** [noranbear/how-about-e-medicine#64]
구현할 기능의 위치와 대상
--
- medidetail.html
- 담기 버튼의 사용 기한 입력 창

구현할 기능 내용
--
- 추가하기 버튼을 누를 시, 
  - 해당 약을 db에 넣기
  - 사용기한을 db에 넣기

구현 방법
--

참고 사항
--

**Comment by najune** [comment]
제가 할게요
